### PR TITLE
Add masc4masc logo to nav and audio player, change joshspace to masc4masc

### PR DESCRIPTION
**Pull request by ckduane**

### CODE REVIEW

**Comment by ckduane** [comment]
oh! josh also requests the heroku URL be changed to masc4mascband.herokuapp.com

**Comment by kedskeds** [comment]
http://masc4mascband.herokuapp.com/

**Comment by kedskeds** [comment]
this looks 👍! is it ready to be merged?

**Comment by ckduane** [comment]
Yah! Merge that pupper!

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request merged**
